name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: run a multi-line scripts or Commands
        run: |
          node -v
          npm -v
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Directory
      PowerShell
        run: Get-Location
      -name: Directory Bash
        run: pwd
        shell: bash
